name: mypy

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install Dependencies
        run: |
          pipenv install