name: Pipeline

on: [ push ]

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Cache pipenv
        uses: actions/cache@v2
        env:
          cache-name: cache-pipenv
        with:
          path: /home/runner/.local/share/virtualenvs/
          key: ${{ runner.os }}-${{ hashFiles('Pipfile.lock') }}


      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Install Dependencies
        run: |
          pipenv install --dev

      - name: Run mypy
        run: |
          pipenv run mypy -m pyreaqtive --config-file mypy.ini

      - name: Run Tests
        run: |
          pipenv run pytest